A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('',views.AboutView.as_view(), name='about'),
]

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
mobile_urlpatterns = [
    path('login-mobile/', views.UserLoginMobileView.as_view(), name='login_mobile'),
    path('verify-otp/', views.VerifyOtpCodeMobileView.as_view(), name='verify_otp'),

]
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('profile/<str:username>/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('edit-profile/<str:username>/', views.UserEditProfileView.as_view(), name='edit_profile'),
    path('forgot-password/', views.ForgotPasswordView.as_view(), name='forgot_password'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('', include((mobile_urlpatterns, ''))),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.ContactView.as_view(), name='contact'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),

]

templates/include/messages.html
{% if messages %}
    {% for message in messages %}
    	<div class="alert alert-{{ message.tags }}" role="alert">
  {{ message }}
</div>
    {% endfor %}
    
{% endif %} 

templates/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}">My Weblog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
                </li>

                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:profile' request.user.username %}">Profile</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'contact:contact' %}">Contact</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>