A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
mobile_urlpatterns = [
    path('login-mobile/', views.UserLoginMobileView.as_view(), name='login_mobile'),
    path('verify-otp/', views.VerifyOtpCodeMobileView.as_view(), name='verify_otp'),

]
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('profile/<str:username>/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('edit-profile/<str:username>/', views.UserEditProfileView.as_view(), name='edit_profile'),
    path('forgot-password/', views.ForgotPasswordView.as_view(), name='forgot_password'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('', include((mobile_urlpatterns, ''))),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create-new-post/', views.CreatePostView.as_view(), name='post-create'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('delete/<slug:slug>/', views.PostDeleteView.as_view(), name='post-delete'),
    path('edit/<slug:slug>/', views.PostUpdateView.as_view(), name='post-update'),

    path('category/lists/', views.PostCategoryListView.as_view(), name='post-category-lists'),
    path('category/<slug:slug>/', views.PostCategoryDetailView.as_view(), name='single_category'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostReplyCommentView.as_view(), name='post-reply-comment'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .manager import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, max_length=255)
    full_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=11, unique=True)
    username = models.CharField(max_length=50, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    user_profile_image = models.ImageField(upload_to='profile/images/', null=True, blank=True)
    bio = models.TextField(max_length=500, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['username', 'email', 'full_name']
    readonly_fields = ['is_active', 'is_admin', 'is_superuser']
    objects = UserManager()

    def __str__(self):
        return self.full_name

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class OtpCode(models.Model):
    code = models.PositiveIntegerField()
    mobile = models.CharField(max_length=11)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} {} '.format(self.mobile, self.code)

accounts/views.py
from datetime import datetime, timedelta, timezone
from random import randint

from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, View, FormView, UpdateView

from posts.models import Post
from utils import send_sms_code
from .forms import UserRegistrationForm, LoginForm, EditProfileForm, MobileLoginForm, VerifyOtpCodeForm, \
    SendForgotPasswordSmsForm, ForgotPasswordForm
from .models import User, OtpCode


class UserLoginView(FormView):
    template_name = 'accounts/login.html'
    form_class = LoginForm

    def form_valid(self, form):
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        if user is not None:
            login(self.request, user)
            messages.success(self.request, 'You are now logged in.', 'success')

            return redirect('accounts:profile', user.username)

        messages.error(self.request, 'Invalid username or password.', 'danger')
        return redirect('accounts:login')


class UserRegisterView(View):
    template_name = 'accounts/register.html'
    class_form = UserRegistrationForm

    def get(self, request):
        return render(request, self.template_name, {'form': self.class_form()})

    def post(self, request):
        form = self.class_form(request.POST)
        if form.is_valid():
            User.objects.create_user(username=form.cleaned_data.get('username'),
                                     full_name=form.cleaned_data.get('full_name'),
                                     email=form.cleaned_data.get('email'), password=form.cleaned_data.get('password'),
                                     phone_number=form.cleaned_data.get('phone_number'))
            messages.success(request, 'Account created successfully', extra_tags='success')
            return redirect('accounts:login')
        messages.error(request, form.errors, extra_tags='danger')
        return render(request, self.template_name, {'form': form})


class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['user_information'] = User.objects.get(username=kwargs['username'])
        context['user_post'] = Post.objects.filter(author=context['user_information']).order_by('-created_at')
        context['unpublished_posts'] = context['user_post'].filter(is_published=False)

        return context


class UserLogoutView(LoginRequiredMixin, View):

    def get(self, request):
        logout(request)
        messages.success(request, 'You are now logged out.', 'success')

        return redirect('accounts:login')


class UserEditProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'accounts/edit_profile.html'
    model = User
    form_class = EditProfileForm

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        if form.is_valid():
            messages.success(self.request, 'You are now edited successfully', extra_tags='success')
            form.save()
            return redirect('accounts:profile', self.request.user.username)


class UserLoginMobileView(View):
    template_name = 'mobile/login-mobile.html'
    form_class = MobileLoginForm

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class()})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            mobile = form.cleaned_data['mobile']
            mobile_in_database = User.objects.filter(phone_number=mobile).exists()
            if OtpCode.objects.filter(mobile=mobile).exists():
                messages.error(self.request, 'we sent you a code if you did not resave it please try 2 minute later',
                               'danger')
                return redirect('accounts:login_mobile')
            if mobile_in_database:
                random_number = randint(1000, 9999)
                OtpCode.objects.create(mobile=mobile, code=random_number)
                send_sms_code(mobile=mobile, code=random_number)
                request.session['user_login_data'] = {
                    'mobile': mobile,
                    'otp_code': random_number,
                }
                messages.success(self.request, 'The code sent to your mobile', 'success')
                return redirect('accounts:verify_otp')

            messages.error(self.request, 'invalid phone number or you have not registered yet!', 'danger')
            return redirect('accounts:login_mobile')
        return render(request, self.template_name, {'form': form})


class VerifyOtpCodeMobileView(View):
    template_name = 'mobile/verify_otp_code.html'
    from_class = VerifyOtpCodeForm

    def get(self, request):
        return render(request, self.template_name, {'form': self.from_class()})

    def post(self, request):
   
        form = self.from_class(request.POST)
        user_data = request.session.get('user_login_data')
        otp_code = OtpCode.objects.get(code=user_data['otp_code'])
        expire_otp_code = datetime.now(tz=timezone.utc) + timedelta(minutes=2)

        if form.is_valid():
            code = form.cleaned_data.get('code')
            if otp_code.code == code:
                if otp_code.created_at < expire_otp_code:
                    otp_code.delete()
                    messages.error(request, 'OTP code expired.', 'danger')
                    return redirect('accounts:login_mobile')
                user = User.objects.get(phone_number=user_data['mobile'])
                user.backend = 'django.contrib.auth.backends.ModelBackend'
                login(request, user)
                messages.success(request, 'You are now logged in', 'success')
                otp_code.delete()
                request.session['user_login_data'].clear()
                return redirect('accounts:profile', user.username)
            messages.success(request, 'Your otp code is invalid', 'danger')
            return redirect('accounts:verify_otp')
        return render(request, self.template_name, {'form': form})


class ForgotPasswordView(FormView):
    template_name = 'password/forgot-password.html'
    form_class = SendForgotPasswordSmsForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        random_number = randint(1000, 9999)
        phone_number = form.cleaned_data['phone_number']
        user = User.objects.filter(phone_number=phone_number).exists()
        if not user:
            messages.error(self.request, 'This user is not exist !!!', 'danger')
            return redirect('accounts:forgot_password')
        else:
            OtpCode.objects.create(mobile=phone_number, code=random_number)
            send_sms_code(mobile=phone_number, code=random_number)
            self.request.session['forgot_password'] = {
                'phone': phone_number,
                'code': random_number,
            }
            messages.success(self.request, 'We sent you an Otp code', 'success')
            return redirect('accounts:password_reset')


class PasswordResetView(FormView):
    template_name = 'password/reset-password.html'
    form_class = ForgotPasswordForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user_forgot_password_info = self.request.session.get('forgot_password')
        verification_code = form.cleaned_data['verification_code']
        password = form.cleaned_data['new_password']

        otp_code = OtpCode.objects.filter(code=verification_code).exists()
        if not otp_code:
            messages.error(self.request, 'OTP code does not exist', 'danger')
            return redirect('accounts:password_reset')
        else:
            user = User.objects.get(phone_number=user_forgot_password_info['phone'])
            user.set_password(password)
            user.save()
            OtpCode.objects.filter(code=verification_code).delete()
            self.request.session['forgot_password'].clear()
            messages.success(self.request, 'Your password changed successfully', 'success')
        return redirect('accounts:login')

accounts/templates/accounts/edit_profile.html
{% extends 'main.html' %}

{% block main %}
    <!-- Main Content -->
    <div class="col-md-9 py-4">
        <h2>Edit Profile</h2>
        <div class="card p-4">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                <div class="d-flex gap-2">
                    <input type="submit" class="btn btn-primary" value="Save Changes">
                    <a href="{% url 'accounts:profile' request.user.username %}" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'main.html' %}

{% block main %}


    <div class="col-md-7 ">
        <div class="login-card">
            <h3 class="text-center mb-4">Login</h3>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label class="form-label">Username OR phone number</label>
                    {{ form.username }}
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    {{ form.password }}
                </div>
                <input type="submit" class="btn btn-primary w-100" value="Login">
            </form>
            <h6 class="w-100 text-center m-3">OR</h6>
            <a href="{% url 'accounts:login_mobile' %}">
                <button type="submit" class="btn btn-info w-100">Login with phone</button>
            </a>
            <p class="text-center mt-3 small"><a href="{% url 'accounts:forgot_password' %}">Forgot your
                password?</a></p>
            <p class="text-center mt-3 small">Need an account? <a href="{% url 'accounts:register' %}">Register</a></p>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'main.html' %}
{% load static %}
<div class="container-fluid mt-4">
    <div class="row">

        {% block main %}

            <div class="col-md-6 py-4">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h2>My Posts</h2>
                    <hr>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'posts:post-create' %}" class="btn btn-primary">Create New Post</a>
                    {% endif %}
                </div>

                <div class="post-list">
                    {% for post in user_post %}
                        {% if post.is_published %}
                            <div class="card mb-3">
                                <div class="row g-0">
                                    <div class="col-md-4">
                                        <img src="{{ post.featured_image.url }}" class="img-fluid rounded-start"
                                             alt="Post 1">
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ post.title }}</h5>
                                            <p class="card-text">{{ post.content|truncatewords:50 |safe }}</p>
                                            <p class="card-text"><small class="text-muted">Category: <a
                                                    href="{{ post.categories.get_absolute_url }}">{{ post.categories }}</a></small>
                                            </p>
                                            <p class="card-text"><small
                                                    class="text-muted">{{ post.created_at|timesince }}
                                                ago</small></p>
                                            <a href="{{ post.get_absolute_url }}" class="btn btn-primary btn-sm">Read
                                                More</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% empty %}
                        <div class="col-md-4">
                            <h5 class="m-5">There is no post yet !</h5>
                        </div>

                    {% endfor %}

                </div>
            </div>

            <!-- Right Sidebar (User Profile) -->
            <div class="col-md-3 user-info-sidebar">
                <h5>User Profile</h5>

                <div class="text-center">
                    {% if user_information.user_profile_image %}
                        <img src="{{ user_information.user_profile_image.url }}" class="rounded-circle mb-3"
                             alt="Profile Picture">
                    {% else %}
                        <img src="{% static 'profile/default-profile.png' %}" class="rounded-circle mb-3"
                             alt="Profile Picture">
                    {% endif %}
                    <h6>{{ user_information.full_name }}</h6>
                    <p class="small"><strong>Email:</strong> {{ user_information.email }}</p>
                    <p class="small"><strong>Last Login:</strong> {{ user_information.last_login|timesince }}</p>
                    <p class="small"><strong>Posts:</strong> {{ user_post|length }}</p>
                    <p class="small text-danger"><strong>Unpublished:</strong> {{ unpublished_posts|length }}</p>


                    {% if user_information.bio %}
                        <p class="small"><strong>Bio:</strong> {{ user_information.bio }}</p>
                    {% else %}
                        <p class="small"><strong>Bio:</strong> tell us about yourself ...</p>
                    {% endif %}
                    {% if request.user.is_authenticated and user_information.id == request.user.id %}
                        <a href="{% url 'accounts:edit_profile' username %}">
                            <button class="btn btn-primary mt-2">Edit Profile</button>
                        </a>

                    {% endif %}
                </div>


            </div>
            </div>
        {% endblock %}
</div>

accounts/templates/accounts/register.html
{% extends 'main.html' %}



{% block main %}

    <div class="col-md-5">
        <div class="register-card">
            <h3 class="text-center mb-6">Register</h3>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary w-100" value="Register">


            </form>
            <p class="text-center mt-3 small">Have an account? <a href="{% url 'accounts:login' %}">Login</a></p>
        </div>
    </div>


{% endblock %}