A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create-new-post/', views.CreatePostView.as_view(), name='post-create'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('delete/<slug:slug>/', views.PostDeleteView.as_view(), name='post-delete'),
    path('edit/<slug:slug>/', views.PostUpdateView.as_view(), name='post-update'),

    path('category/lists/', views.PostCategoryListView.as_view(), name='post-category-lists'),
    path('category/<slug:slug>/', views.PostCategoryDetailView.as_view(), name='single_category'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostReplyCommentView.as_view(), name='post-reply-comment'),
]

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon-16x16.png' %}">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    {% block seo %}

    {% endblock %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<!-- Navbar -->
{% include 'include/navbar.html' %}
{% include 'include/messages.html' %}

<div class="container-fluid mt-4">
    <div class="row">
        <!-- Sidebar -->

        <!-- Sidebar -->
        <div class="col-md-3 sidebar">
            <div class="mb-4">
                <input type="text" class="form-control search-bar" placeholder="Search...">
            </div>
            <div class="mb-4">
                <h5 class="d-flex justify-content-between">
                    <span>Categories</span>
                    <a href="{% url 'posts:post-category-lists' %}"> <span class="text-white">Show All</span></a>
                </h5>

                {% for category in categories %}
                    <ul class="list-group category-list">
                        <li class="list-group-item"><a href="{% url 'posts:single_category' category.slug %}"
                                                       class="text-decoration-none text-white">{{ category.title }}</a>
                        </li>

                    </ul>
                {% endfor %}


            </div>
            <div>
                <h5>About</h5>
                <p class="small">{{ abouts.body }}</p>
            </div>
        </div>


        <!-- Main Content -->
        {% block main %}

        {% endblock %}
    </div>
</div>


</body>
</html>