A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
mobile_urlpatterns = [
    path('login-mobile/', views.UserLoginMobileView.as_view(), name='login_mobile'),
    path('verify-otp/', views.VerifyOtpCodeMobileView.as_view(), name='verify_otp'),

]
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('profile/<str:username>/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('edit-profile/<str:username>/', views.UserEditProfileView.as_view(), name='edit_profile'),
    path('forgot-password/', views.ForgotPasswordView.as_view(), name='forgot_password'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('', include((mobile_urlpatterns, ''))),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create-new-post/', views.CreatePostView.as_view(), name='post-create'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('delete/<slug:slug>/', views.PostDeleteView.as_view(), name='post-delete'),
    path('edit/<slug:slug>/', views.PostUpdateView.as_view(), name='post-update'),

    path('category/lists/', views.PostCategoryListView.as_view(), name='post-category-lists'),
    path('category/<slug:slug>/', views.PostCategoryDetailView.as_view(), name='single_category'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostReplyCommentView.as_view(), name='post-reply-comment'),
]

posts/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from accounts.models import User
from django.shortcuts import reverse
from ckeditor_uploader.fields import RichTextUploadingField


class BaseTimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Seo(models.Model):
    page_title = models.CharField(max_length=70, help_text='Recommended 50-70 characters ')
    slug = models.SlugField(unique=True, max_length=200, help_text='Recommended 50-70 characters ')
    meta_description = models.TextField(
        max_length=160,
        blank=True,
        null=True,
        help_text="Recommended: 150-160 characters for meta description"
    )

    class Meta:
        verbose_name = "SEO Metadata"
        verbose_name_plural = "SEO Metadata Entries"
        abstract = True

    def clean(self):

        if not self.slug:
            self.slug = slugify(self.page_title)
        if self.meta_description and len(self.meta_description) > 160:
            raise ValidationError('Meta description must be 160 characters or less.')

    def save(self, *args, **kwargs):
        self.clean()
        super(Seo, self).save(*args, **kwargs)


class Category(BaseTimeStamp, Seo):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = RichTextField(max_length=200)

    # TODO:add a summery about category
    class Meta:
        verbose_name_plural = 'Categories'
        verbose_name = 'Category'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # TODO:set if slug have space automatically remove it
        if not self.slug:
            self.slug = slugify(self.title)
            self.save()
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single_category', kwargs={'slug': self.slug})


# Create your models here.
class Post(BaseTimeStamp, Seo):
    categories = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, related_name='categories')
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=20, unique=True, blank=True)
    content = RichTextUploadingField()
    featured_image = models.ImageField(upload_to='featured-images/')
    breaking_news = models.BooleanField(default=False)
    is_published = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='author')
    keywords = models.CharField(null=True, blank=True, verbose_name='separated with comma (,)')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            self.save()
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post-detail', kwargs={'slug': self.slug})


class Comment(BaseTimeStamp):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_comment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comment')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    is_reply = models.BooleanField(default=False)
    content = models.TextField()

    def __str__(self):
        return '{} - {}'.format(self.author, self.content[:30])

posts/forms.py
from django import forms
from ckeditor.fields import RichTextField
from posts.models import Post, Category, Comment


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'featured_image', 'categories']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'featured_image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            'categories': ''
        }


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 3,
                       'placeholder': 'Write your comment...'}),
        }
        labels = {
            'content': ''
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Write your reply...'}),

        }
        labels = {'content': ''}

posts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, CreateView, DeleteView, UpdateView, ListView, View

from posts.models import Post, Category, Comment
from .forms import CreatePostForm, CommentCreateForm, CommentReplyForm


class PostDetailView(View):
    template_name = 'posts/detail_post.html'

    context_object_name = 'post'
    comment_form = CommentCreateForm
    reply_form = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        """
        because we need it in all method so we use setup
        """

        self.post_instance = get_object_or_404(Post, slug=kwargs['slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        comments = Comment.objects.filter(post=self.post_instance, is_reply=False)
        return render(request, self.template_name,
                      context={'post': self.post_instance, 'comments': comments, 'comment_form': self.comment_form,
                               'reply_form': self.reply_form})

    """
    method_decorator is a function (actually a class acting as a decorator factory) in Django used to convert a function-based decorator into a method-based decorator. This is important when you want to apply decorators to methods within Django class-based views.
The Problem:
Regular function decorators don't work directly on methods of class-based views because the decorator receives the function itself, not the method bound to an instance. This loses the crucial self argument, preventing the method from accessing the view's instance and its attributes.
The Solution:
method_decorator solves this by creating a wrapper that correctly handles the self argument when the decorated method is called.
    """

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.comment_form(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, 'Your comment submitted successfully', extra_tags='success')
        return redirect('posts:post-detail', slug=kwargs['slug'])


class PostReplyCommentView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, id=kwargs['post_id'])
        comment = get_object_or_404(Comment, id=kwargs['comment_id'])
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.author = request.user
            reply.post = post
            reply.parent = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, 'Your reply submitted successfully', extra_tags='success')

        return redirect('posts:post-detail', slug=post.slug)


class CreatePostView(LoginRequiredMixin, CreateView):
    template_name = 'posts/create_new_post.html'
    model = Post
    form_class = CreatePostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, 'Post created successfully', 'success')
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'After review it will be shown in your profile',
                         'info')
        return reverse_lazy('accounts:profile', kwargs={'username': self.request.user.username})


class PostDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'posts/delete_post.html'
    model = Post

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, slug=kwargs['slug'])
        return super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = self.post_instance
        return context

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        post = self.post_instance
        if post.author != user:
            messages.error(request, f'You are not authorized to delete this post.this post belongs to {post.author}',
                           'danger')
            return redirect('accounts:profile', request.user.username)
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        messages.success(self.request, 'Post deleted successfully', 'success')
        return reverse_lazy('accounts:profile', kwargs={'username': self.request.user.username})


class PostUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'posts/update_post.html'
    model = Post
    form_class = CreatePostForm

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        post = get_object_or_404(Post, slug=kwargs['slug'])
        if post.author != user:
            messages.error(request, 'You are not authorized to edit this post.', 'danger')
            return redirect('accounts:profile', user.username)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, 'Post updated successfully', 'success')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('accounts:profile', kwargs={'username': self.request.user.username})


class PostCategoryListView(ListView):
    template_name = 'category/categories.html'
    model = Category
    context_object_name = 'categories'


class PostCategoryDetailView(DetailView):
    template_name = 'category/single_category.html'
    model = Category
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.get(slug=self.kwargs['slug'])
        context['posts'] = Post.objects.filter(categories=context['category'])
        return context

posts/templates/posts/create_new_post.html
{% extends 'main.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block main %}


    <div class="col-md-7 py-4">

        <!-- Main Content (Create Post Form) -->

        <h2>Create New Post</h2>
        <div class="card p-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <input type="submit" value="publish post" class="btn btn-primary">
            </form>
        </div>
    </div>

{% endblock %}

posts/templates/posts/delete_post.html
{% extends 'main.html' %}

{% block title %}
	{{ post.title }}
{% endblock %}
{% block main %}

    <div class="col-md-9 py-4">
        <h2>Delete Post</h2>
        <div class="card p-4">
            <h5>Are you sure you want to delete this post?</h5>
            <div class="mb-3">
                <p><strong>Title:</strong> {{ post.title }}</p>
                <p><strong>Category:</strong> {{ post.categories }}</p>
                <p><strong>Posted:</strong> {{ post.created_at|timesince }} ago</p>
                <p><strong>Content Preview:</strong> {{ post.content |safe|truncatewords:10 }}</p>
                <p><strong>Image:</strong> <a href="{{ post.featured_image.url }}" target="_blank">View
                    image</a></p>
            </div>
            <form method="post">
                {% csrf_token %}

                <h4>Are you sure you want to delete
                    <mark>"{{ object }}"</mark>
                    ?
                </h4>
                <br>

                <div class="d-flex gap-2">
                    <input type="submit" class="btn btn-danger" value="Yes, Delete Post">
                    <a href="{% url 'accounts:profile' post.author.username %}" class="btn btn-secondary">Cancel</a>
                </div>
            </form>

        </div>
    </div>
{% endblock %}

posts/templates/posts/detail_post.html
{% extends 'main.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}

{% block seo %}
    <meta name="description"
          content="{{ post.meta_description }}">
    <meta name="keywords" content="news, technology, sports, weblog, blog, updates, articles">
    <meta name="author" content="{{ post.author }}">



    <meta property="og:title" content="{{ post.page_title }}">
    <meta property="og:description"
          content="{{ post.meta_description }}">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.myweblog.com/">

    <meta property="og:site_name" content="My Weblog">
{% endblock %}

{% block main %}
    <div class="col-md-9 py-4">
        <!-- Post Section -->
        <div class="news-card mb-4">
            <img src="{{ post.featured_image.url }}" class="card-img-top post-page-img" alt="Post Image"
                 data-bs-toggle="modal" data-bs-target="#imageModal">
            <div class="card-body">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="text-muted mb-3">Posted by <a
                            href="{% url 'accounts:profile' post.author.username %}">{{ post.author }} </a>| {{ post.created_at|timesince }}
                        ago</p>
                    <p class="card-text">{{ post.content|safe }}</p>
                    {% if request.user == post.author %}
                        <div class="d-flex justify-content-end gap-2 mt-4">
                            <a href="{% url 'posts:post-delete' post.slug %}">
                                <button class="btn btn-danger">Delete Post</button>
                            </a>
                            <a href="{% url 'posts:post-update' post.slug %}">
                                <button class="btn btn-primary">Update Post</button>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>


            <!-- Comments Section -->
            <div class="card mb-4">
                <div class="card-body">
                    <h3 class="card-title mb-4">Comments</h3>

                    <!-- Existing Comments -->
                    <div class="mb-4">
                        <!-- Top-level Comment -->
                        {% for comment in comments %}
                            <div class="comment mb-3 p-3 bg-light rounded">
                                <p class="mb-1"><strong>{{ comment.author |capfirst }} |</strong> <small
                                        class="text-muted">{{ comment.created_at|timesince }} ago</small></p>
                                <p class="mb-3">{{ comment.content }}</p>
                                <!-- Reply Form -->
                                {% if request.user.is_authenticated %}
                                    <form class="reply-form" method="post"
                                          action="{% url 'posts:post-reply-comment' post.id comment.id %}">
                                        <div class="mb-2">
                                            {% csrf_token %}
                                            {{ reply_form }}
                                        </div>
                                        <button type="submit" class="btn btn-outline-primary btn-sm">Reply</button>
                                    </form>

                                {% endif %}
                            </div>


                            <!-- Reply to Jane's Comment -->



                            {% with replies=comment.replies.all %}
                                {% for reply in replies %}
                                    <div class="comment reply-comment mb-3 p-3 bg-info-subtle rounded ms-4">
                                    <p class="mb-1"><strong>{{ reply.author |capfirst }} |</strong> <small
                                            class="text-muted">{{ reply.created_at|timesince }}
                                        ago</small>
                                    </p>
                                    <p class="mb-3">{{ reply.content }}</p>
                                    <!-- Reply Form -->
                                    {% if request.user.is_authenticated %}
                                        <form class="reply-form" method="post"
                                              action="{% url 'posts:post-reply-comment' post.id comment.id %}">
                                            <div class="mb-2">
                                                {% csrf_token %}
                                                {{ reply_form }}
                                            </div>
                                            <button type="submit" class="btn btn-outline-primary btn-sm">Reply</button>
                                        </form>
                                    {% endif %}
                                {% endfor %}
                            {% endwith %}
                        </div>
                        {% empty %}
                            <div class="comment mb-3 p-3 bg-light rounded">
                                <p>There is no comment yet!</p>
                            </div>
                        {% endfor %}




                        <!-- New Comment Form -->
                        <h4 class="mb-3">Add a Comment</h4>
                        {% if request.user.is_authenticated %}
                            <form class="new-comment-form" method="post">
                                {% csrf_token %}
                                <div class="mb-3">
                                    {{ comment_form }}
                                    <input type="submit" class="btn btn-primary m-3" value="Post Comment">
                                </div>
                            </form>
                        {% else %}
                            <div class="mb-3">
                                <p class="alert alert-danger">Only logged-in users can comment.</p>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

posts/templates/posts/single_post.html
{% extends 'main.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block main %}
    <div class="col-md-9 py-4">
        <!-- Post Section -->
        <div class="news-card mb-4">

            <img src="{{ post.featured_image.url }}" class="card-img-top post-page-img" alt="Post Image"
                 data-bs-toggle="modal" data-bs-target="#imageModal">
            <div class="card-body">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="text-muted mb-3">Posted by <a
                            href="{% url 'accounts:profile' post.author.username %}">{{ post.author }} </a>| {{ post.created_at|timesince }}
                        ago</p>
                    <p class="card-text">{{ post.content }}</p>
                    {% if request.user == post.author %}
                        <div class="d-flex justify-content-end gap-2 mt-4">
                            <a href="{% url 'posts:post-delete' post.slug %}">
                                <button class="btn btn-danger">Delete Post</button>
                            </a>
                            <a href="{% url 'posts:post-update' post.slug %}">
                                <button class="btn btn-primary">Update Post</button>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>


            <!-- Comments Section -->
            <div class="card mb-4">
                <div class="card-body">
                    <h3 class="card-title mb-4">Comments</h3>

                    <!-- Existing Comments -->
                    <div class="mb-4">
                        <!-- Top-level Comment -->


                        {% for comment in comments %}
                            <div class="comment mb-3 p-3 bg-light rounded">
                                <p class="mb-1"><strong>{{ comment.author |capfirst }}</strong> <small
                                        class="text-muted">{{ comment.created_at|timesince }} ago</small></p>
                                <p class="mb-3">{{ comment.content }}</p>
                                <!-- Reply Form -->
                                <form class="reply-form">
                                    <div class="mb-2">
                                    <textarea class="form-control" rows="2" placeholder="Write a reply..."
                                              required></textarea>
                                    </div>
                                    <button type="submit" class="btn btn-outline-primary btn-sm">Reply</button>
                                </form>
                            </div>


                            <!-- Reply to Jane's Comment -->


                            <div class="comment reply-comment mb-3 p-3 bg-info-subtle rounded ms-4">
                                {% for reply in comment.replies.all %}
                                    <p class="mb-1"><strong>{{ reply.author |capfirst }}</strong> <small
                                            class="text-muted">{{ reply.created_at|timesince }}
                                        ago</small>
                                    </p>
                                    <p class="mb-3">{{ reply.content }}</p>
                                    <!-- Reply Form -->
                                    <form class="reply-form">
                                        <div class="mb-2">
                                    <textarea class="form-control" rows="2" placeholder="Write a reply..."
                                              required></textarea>
                                        </div>
                                        <button type="submit" class="btn btn-outline-primary btn-sm">Reply</button>
                                    </form>
                                {% endfor %}
                            </div>








                        {% endfor %}

                        <!-- New Comment Form -->
                        <h4 class="mb-3">Add a Comment</h4>
                        <form class="new-comment-form">
                            <div class="mb-3">
                            <textarea class="form-control" rows="3" placeholder="Write your comment..."
                                      required></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Post Comment</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

posts/templates/posts/update_post.html
{% extends 'main.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}

<!-- Main Content (Update Post Form) -->
{% block main %}
    <div class="col-md-9 py-4">
        <h2>Update Post</h2>
        <div class="card p-4">
            <form action="" method="post" class="form-control">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}

                <input type="submit" class="btn btn-success" value="update">
            </form>
        </div>


    </div>
{% endblock %}